### ISSUE TITLE
A couple of yup features that would be nice to have

### ISSUE THREAD

**Issue by JohnDavisSDS** [vriad/zod#14]
I'm really impressed with this project and its ease of use.  There are a couple of features from yup that would be really useful.

#1. yup.object().noUnknown() - This feature causes yup to throw an error on validation if there's a property on the object that doesn't match the schema
#2. ValidationError.path - When yup throws a validation error, it specifies where in the schema that error occurred which can be very helpful for large schemas

**Comment by vriad** [comment]
Thanks! I created separate dedicated issues for each of these (#16 and #17). Should get around to implementing both of these relatively soon.

**Comment by vriad** [comment]
@JohnDavisSDS zod@1.0.11 includes vastly improved error handling, check out the Errors section of the Readme for details 🤙

**Comment by vriad** [comment]
@JohnDavisSDS Zod also now supports the equivalent of `.noUnknown`. 

Or more specifically, I clarified in the docs that "no unknown keys" is the default behavior, since this hews more closely to how TypeScript works. You're now able to all unknown keys by calling `.nonstrict()` on any object schema 👍
