### ISSUE TITLE
Is it possible to add default values? 

### ISSUE THREAD

**Issue by escobar5** [vriad/zod#18]
Hi, I love this library, it's perfect for the project I'm currently working on. I come from **Joi**, and it has a `.default('value')` for specifying a default value if not set. Does this library have something similar? is that a possibility?

Thanks

**Comment by vriad** [comment]
I don't want to do this at the moment, since it would mark a subtle shift from being a "parse" tool into a "cast" tool. Casting gets messy quickly what with default values, required/non-required keys, recursive/cyclical types, primitive castings, etc. I always found yup/joi casting difficult to reason about. 

I'd recommend building a default/validation pipeline by combining Zod with something like lodash. You can use`_.defaultsDeep` to set defaults on an unvalidated object, like so:

```ts
import * as _ from 'lodash';
import * as z from "zod";

const dogDefaults = {
  breed: "Unknown"
}

const Dog = z.object({
  breed: z.string(),
  age: z.number()
});
type Dog = z.TypeOf<typeof Dog>;

const unknownDog: any = { /* whatever */ };

const cleanAndValidate = (rawData: unknown)=>{
  return Dog.parse(_.defaultsDeep(unknownDog, dogDefaults)); 
}

const validDog = cleanAndValidate(unknownDog); 
// typeof validDog => Dog
```

**Comment by tuchk4** [comment]
I would like to push `defaults` feature into the zod.

zod is really nice tool, but it is hard to use it without the default values.

For example:

1. There is the schema:

```ts
const LibrarySchema = z.object({
  namespace: z.string().optional(),
  components: z
    .record(
      z.object({
        names: z.string(),
      }),
    )
    .optional(),
});

type ILibrarySchema = z.infer<typeof LibrarySchema>;

```

2. `ILibrarySchema` equals to:

```ts
type ILibrarySchema = {
    namespace?: string | undefined;
    components?: Record<string, {
        names: string;
    }> | undefined;
}
```

so all fields are optional, as expected.

3. Then I would like to fill schema with the default values

```ts
const parsed = LibrarySchema.parse(raw);
const config = withDefaults(parser);
```

Here is the problem. I can't correctly write the type for `withDefaults` function.
```
const withDefaults = (config:ILibrarySchema): ???  => { ... };
```
 It is not possible to return `ILibrarySchema` since it has optional fields, but I would like to return `config` with the default values, that means, that some fields should not be optional.
