### ISSUE TITLE
Ability to require one or another field, or require one field if another is provided

### ISSUE THREAD

**Issue by ablankenship10** [vriad/zod#190]
I read through the readme and nothing popped out as supporting this functionality, apologies if I missed something.

The Joi library contains the .with() and .xor() methods which allows you to define whether or not fields are required based on whether or not another field exists. This would be helpful in a case where I want to allow a user to signup with either an `email` or `phoneNumber` field, or a `password` or `googleAuthToken`, or that both `password` and `repeatPassword` exist (and match also?)

You can see how this works in the example in their documention: https://joi.dev/api/?v=17.2.1#example

**Comment by JVictorV** [comment]
+1, that would help me with my problem too https://github.com/vriad/zod/issues/181

**Comment by vriad** [comment]
I think Yup's `.with` approach is interesting but too hard to reason about. I recommend implementing all of these things with custom refinements. The `password`/`confirmPassword` approach is specifically addressed here: https://github.com/vriad/zod#custom-validation

@JVictorV Your issue is a little different, see the answer there by @pkerschbaum

**Comment by KaKi87** [comment]
Hello,

What are the simplest ways to do implement Joi's `.or`, `.xor`, `.and`, `.with` & `.without` using `zod` as of today ?

Thanks
