### ISSUE TITLE
Date type handling?

### ISSUE THREAD

**Issue by joe-bruce** [vriad/zod#30]
This lib looks like a really nice approach. I don't see support for `Date` types, though. Do you have a plan to support them?

**Comment by vriad** [comment]
Implemented 👍 

Take it for a spin and let me know if you have any issues.

**Comment by joe-bruce** [comment]
Thanks! I see `Date` validation, but was hoping for `Date` parsing. (Something like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse)
Am I barking up the wrong tree?

**Comment by vriad** [comment]
Hey Joe,

So you want to be able to pass in, say, an ISO string to a Date field and have `.parse` return a proper Date object in its place?

```ts
const Person = z.object({
  createdAt: z.date()
})

const person = Person.parse({
  createdAt: `2020-04-09T22:11:52.520Z`
}) // passes

person.createdAt // Date object
```

I'm trying to keep this library from becoming a casting library, since casting is generally messy and difficult, especially when you're dealing with static types. Currently the above code wouldn't pass static validation, since`zod` expects `Person.createdAt` to be a `Date`. To get it to work, I'd have to create a variant of the inferred schema type that changes all `Date` fields to `Date | string`, to accommodate the loosened restrictions on the input to `.parse`. Over time these "loosenings" would get messier and less intuitive.

I'd rather implement this is a refinement string type:

```ts
const Person = z.object({
  createdAt: z.string().refine({ is: 'isoString' });
})
```

I'm already planning to implement other built-in refinement validators (`{ is: 'email' }`, `{ is: 'url' }`, etc.). 

This way you could parse your schema, then be confident that passing `Person.createdAt` into `Date.parse` will return a valid date. Would that work for you?

**Comment by vriad** [comment]
@joe-bruce Closing this for now. If you really prefer a lib that does type coercion check out [myzod](https://github.com/davidmdm/myzod).

**Comment by TroyMorvant** [comment]
Did you ever implement the refinement validation?

**Comment by vriad** [comment]
You can do custom refinements now but there isn't a built-in way to check for valid ISO date strings because that can mean [many different things](https://stackoverflow.com/questions/3143070/javascript-regex-iso-datetime/3143231). I recommend creating a custom refinement using a regex that does exactly what you want.

Zod will also support transformations soon (https://github.com/vriad/zod/issues/100) so the original use case will also be possible.

**Comment by maneetgoyal** [comment]
Was about to request date/time/date-time formats and then stumbled upon this issue. Would it make sense to use [the regex](https://github.com/ajv-validator/ajv/blob/master/lib/compile/formats.js#L37) that AJV is also using? I am thinking of using refinement with these regexes thinking they would be very robust. But looking at the Stackoverflow answer shared above, @vriad do you mean that the regex to correctly handle all those cases is just isn't available yet?

**Comment by vriad** [comment]
Feel free to open this as a separate issue. I'm open to implementing AJV's date/time/date-time regexes as built-ins.

**Comment by maneetgoyal** [comment]
Great :)
