### ISSUE TITLE
Partial Schema Validation

### ISSUE THREAD

**Issue by peterwbeck** [vriad/zod#32]
Hey man!  Great job with the library!  Coming from io-ts I really like how similar the syntax is.   I'm looking for a feature that I have yet to find in any schema validation libraries.  The ability to validate both complete and partial input against a single defined schema.

The use case is this.  I have an API that allows creation and update of a resource.  Both operations need to validate the input.  In the creation case, the input needs to strictly adhere to the schema.  In the update case, any partial input that matches a subset of the schema should be accepted.

I can accomplish this with any schema validation library by creating 2 schemas but my schemas are quite large and this would be painful.  It would be great to be able to either:
- Clone a schema as a "deep partial" in which every nested prop is converted to partial.
- Parse/decode input using a "asPartial" option that allows some (or all) properties to be missing.

Thanks for contributing this library to the community!

**Comment by vriad** [comment]
I definitely want to support this use case. 

In the (recently added) documentation for [Masking](https://github.com/vriad/zod#masking) you can see that I too am extremely annoyed by how poorly cases like this are supported by other libs. As a stopgap solution I added `.omit` and `.pick` methods to object schemas (which may be useful for you if you want to strip `id` or certain nested fields from your `update` endpoint). Unfortunately this doesn't work on recursive schemas yet.

I like your first proposed solution much more than the second. I feel strongly that the schema itself should define a single, unambiguous type that will pass validation. Adding a bunch of config options to `.parse` just muddies the waters. Instead the schema should have methods that let you easily generate variants that do what you want.

I love the idea of a `.partial()` method to make all object keys optional. I would rather keep this shallow for now, since that hews more closely to how how TypeScript's builtin `Partial<>` works. 

I'll look into implementing a `.deepPartial` as well but that's a little harder to do. It would require using a recursive transformation of generic object types, which isn't officially supported by TypeScript. There's a workaround for it but sometimes it can get a little dicey 😅 

If `.deepPartial` turns to be too trick to implement short term, you could use `.partial` in conjunction with `.augment` to accomplish the same thing a deep partial without too much boilerplate.

```ts
const Settings = z.object({
  stayLoggedIn: z.boolean(),
  sessionLength: z.number(),
});

const User = z.object({
  username: z.string(),
  settings: Settings
})


// shallow partial
const PartialUser = User.partial()
type PartialUser = {   // inferred
  username?: string | undefined, 
  settings?: { 
    stayLoggedIn: boolean, // still required
    sessionLength: number  // still required
  } | undefined 
}

// deep partial workaround
const UserUpdatePayload = User.partial().augment({
  settings: User.shape.settings.partial()
})
type PartialUser = {   // inferred
  username?: string | undefined, 
  settings?: { 
    stayLoggedIn?: boolean | undefined,  
    sessionLength?: number | undefined 
  } | undefined 
}
```

None of this is implemented yet of course, but it should be ready soon.

Out of curiosity, are your schemas recursive? Unfortunately none of this would work on a recursive object schema since the current method of declaring a recursive schema involves type casting to a generic `ZodType` wrapper class which means you lose most of the object-specific methods.

**Comment by crazydadz** [comment]
have you tried [myzod](https://www.npmjs.com/package/myzod#partial)? It supports deep partial schemas. It might be what you want?

**Comment by vriad** [comment]
@peterwbeck I just implemented deep and shallow partials. Your use case should be supported in zod@1.2.5 👍

Check out the documentation [here](https://github.com/vriad/zod#partials).

**Comment by peterwbeck** [comment]
Very cool, I think this is a great addition to your library.  I have created my own utility function for io-ts types that recursively traverses a schema and clones it, replacing all types with partial types.  This is working well at the moment.

Another feature you may consider adding.  I used the same clone logic to create another utility method that recursively traverses an io-ts schema and produces a javascript object instance populated with random data matching the schema.  I use this in end-to-end tests to quickly new up an instance of a contract to throw at an endpoint.  Having to maintain these contract instances manually would be a nightmare.
