### ISSUE TITLE
Type-checking methods do not accept `unknown`

### ISSUE THREAD

**Issue by hen-zone** [vriad/zod#36]
As of version `1.2.5`, the `parse`, `is` and `check` methods on `ZodType` expect to receive an argument which is _already_ of the schema's type. This is surprising to me; at version `1.0.15` I was passing `unknown` values to these functions, since the input is of unknown type (typically from IO) and the functions are being called explicity to _discover_ whether the value matches the type.

Since I don't want to incorrectly-type the values before they are checked, it seems the only option here is to use `any`, which from my point of view is strictly worse than `unknown`.

Is there a downside I'm not seeing to permitting `unknown` as input to these functions?

**Comment by hen-zone** [comment]
It looks like the change happened here: https://github.com/vriad/zod/commit/448c3ee6f143e8ba2e6cc278fb3a8c3df4e7db3e#diff-0ef964bb9aca3b847f8b0ecefa74a5c7L54

...but I'm not able to tell from the context what the motivation was.

**Comment by vriad** [comment]
I went back and forth on this. 

I thought it was silly that I didn't get errors when I passed a clearly invalid type into `.parse`, like an object literal or a statically typed value (say, from TypeORM or similar). I don't think it makes sense to wait until runtime to catch these errors if Zod + Typescript has enough information to detect them statically. The downside is users who are parsing untyped objects from an API will need to cast with `as any`. I still think it's a worthwhile tradeoff but I'm willing to reconsider it.

**Comment by hen-zone** [comment]
@vriad I think it would be a good compromise to have the methods accept `T | unknown`. That way we can reject any _obviously_-incorrect values (ie those for which we already have an incompatible type), while allowing users to supply unknown values without resorting to a cast to `any`.

**Comment by nicoespeon** [comment]
Hello there 👋 

I went through the same process as @hen-zone. My rationale is indeed to type 3rd parties data as `unknown`(e.g. the response from a non-typed API).

That will force me to do a runtime check to verify the format is expected, which I can do with zod 🎉 

But now that won't work because `unknown` can't be passed to `check()`. So I need to change the type to `any` to make it work (so I loose the TS protection from using the data directly). That can be fixed with discipline, but I think @hen-zone suggestion can make zod work as expected.

If you want, I could have a look and submit a PR for this change. Is that something you'd consider @vriad ?

_P.S: thanks for the lib, it's exactly what I was looking for_

**Comment by vriad** [comment]
Very happy with this solution. Working on it now.

@nicoespeon I'll take care of it but thanks for offering 👍

**Comment by vriad** [comment]
@hen-zone @nicoespeon Released in zod@1.2.6
