### ISSUE TITLE
Can you provide an example of how to do { stripUnknown: true }?

### ISSUE THREAD

**Issue by talmr-k** [vriad/zod#47]
I'm wondering how to do this option from yum:

`stripUnknown`:remove unspecified keys from objects.

I can pluck or omit, but what if I only want to pick the properties on the ZodObject?

For example:

```
const Animal = z.object({
 name: z.string(),
}),
export type Animal = z.infer<
  typeof Animal
>;
```

But, it so happens that an object such as `{ name: 'tommy', kind: 'cat' }` comes along.  How do I only validate the properties on Animal and drop others like `kind`? 

Since I am returned the same object and .nonstrict allows me to still verify the keys I care about, I would like to be able to drop the unknown keys that are on the object.  

The zod object Animal has a .toJSON which return the shape and I can get keys this way:

`Animal.toJSON().shape['0']`

**Comment by vriad** [comment]
There isn't an equivalent of `stripUnknown` because Zod doesn't do any data transformation.

But it sounds like what you're looking for is `nonstrict` which allows unspecified keys (i.e. `kind` in your example) in the parsing step: https://stackoverflow.com/questions/37579969/how-to-use-multiple-tsconfig-files-in-vs-code

But while this would allow you to parse the object successfully, it doesn't strip away the unspecified keys. Currentlty the `.parse` function returns the exact same object you pass in.
