### ISSUE TITLE
z.function can not be used with z.object

### ISSUE THREAD

**Issue by tuoxiansp** [vriad/zod#49]
version: 1.0.9 | 1.2.5 | 1.5.0

When using z.function with z.object like this:
```
const MouseEvents = z.object({
    onClick: z.function(z.tuple([z.number()]), z.undefined())
})
```
Type error throws:
![image](https://user-images.githubusercontent.com/3960056/81444778-4cf7d680-91aa-11ea-9f2e-396a0427e5c1.png)

**Comment by tuoxiansp** [comment]
#48

**Comment by vriad** [comment]
Thanks for taking initiative on this!

I intentionally didn't make ZodFunction a subclass of ZodType, because I thought the concept of a "function parser" was misleading. But your use case makes sense, so I think it's worth it.

There were a few issues with your code:

- The toJSON method needed to call `args.toJSON()` and `returns.toJSON()` instead of just returning the def.
- You need to separately implement the parsing logic in `parser.ts` for each new ZodType subclass you introduce

I did those things and deployed the changes in zod@1.6 - give it a try and let me know if you have any issues 👍
