### ISSUE TITLE
ZodObject methods (pick, omit, partial, etc.) for intersections and unions of objects

### ISSUE THREAD

**Issue by danenania** [vriad/zod#56]
I've been converting lots of TS types to zod. It's going pretty smoothly. Again, thanks for the _excellent_ work on this lib! But some of the types are fairly complex with nested intersections and unions of object types, and I find myself really wishing I could use the ZodObject methods on these types, especially `pick`, `omit`, and `partial`.

So for a zod definition like this:

```typescript
const schema = z.intersection(
  z.object({key1: z.string()}), 
  z.union([
    z.object({key2: z.string()}),
    z.object({key3: z.string()}),
  ])
);
```

I'd love to be able to do:

```typescript
schema.pick({key1: true, key3: true});
schema.omit({key2: true});
schema.partial();
```

And same for other structures: unions of objects, unions of intersections, etc.

It seems like it could be doable to call them recursively through all levels of nesting with the appropriate subset of keys as long as every intersection/union resolves to an object? Maybe type inference is an issue?

I'm getting around this by breaking up complex types into many constituent ZodObject schemas, and then re-composing them using the object methods as needed, but it would be a lot easier to just call the methods directly on the full schema.

**Comment by vriad** [comment]
You're right that this is possible, but I'm hesitant to do it.

Currently `z.intersection` assumes nothing about the types it's intersecting. Adding a `.omit` or `.pick` method to the ZodIntersection class because it wouldn't make any sense in many cases. For instance, you could intersect two enums like so:

````
const green = z.intersection(z.enum(['red', 'green']), z.enum(['green', 'blue']))
green.pick(??);
```

Pick and omit would only be defined if both arguments to `z.intersection` are objects. There may be some fancy ways of getting around this with method overloading; for instance if you call `z.intersection` with two object schemas it returns a special "ObjectIntersection" class that supports these methods, but that gets untenable fast. 

I don't have any good ideas for solving this currently I'm afraid. I think the approach you described ("breaking up complex types into many constituent ZodObject schemas, and then re-composing them using the object methods as needed") is the ideal way of dealing with complexity in your Zod types. But I do see how it leads to redundant code when you're trying to create slight variants of a complex structure.

**Comment by stuft2** [comment]
Ran into this myself today. It may be good to add a not about this to the README.

**Comment by tommy-schmitz** [comment]
I've just run into a similar issue: trying to pass `z.object(foo).refine(bar)` into `z.discriminatedUnion()` doesn't work because the discriminatedUnion can't see the object underneath the refine.

**Comment by froxx93** [comment]
Quite some time passed since the last statement on this thread. Are there any updates on this?
Picking, omitting, etc. more complex types would still be a great feature to have.

If the basic `.intersection()` function shall remain the way it is to keep simplicity, maybe it's a possibility to create an additional way like `.interactiveIntersection()` and make the object functions executable on those?
