### ISSUE TITLE
Custom validation error?

### ISSUE THREAD

**Issue by rauschma** [vriad/zod#60]
```ts
const stringSchema = z.string();
stringSchema.parse(12); // throws Error('Non-string type: number');
```

Instead throw either:
* `ValidationError('Non-string type: number')`
* `ZodError('Non-string type: number')`

Benefit: You can filter for Zod-specific errors when catching.

**Comment by vriad** [comment]
`.parse` should only ever throw ZodErrors. Unfortunately you need to tell TypeScript this manually - there's no way (that I know of) for the static checker to automatically type the `err` in a try/catch block.

```ts
import * as z from '.';
const stringSchema = z.string();
try {
  stringSchema.parse(12);
} catch (err) {
  console.log(err instanceof z.ZodError); // prints "true"
}
```

If you're not getting the same thing, then that's definitely a bug.

Otherwise you'll have to use something like this to get proper typing (unfortunately)

```ts
try {
  stringSchema.parse(12);
} catch (err) {
  if(err instanceof z.ZodError){
    // handle
  }
}
```

**Comment by rauschma** [comment]
Cool, then it’s just a matter of changing the following line in the readme.

From:

```ts
stringSchema.parse(12); // throws Error('Non-string type: number');
```

To:

```ts
stringSchema.parse(12); // throws ZodError('Non-string type: number');
```

`catch` parameters being untyped is indeed annoying.

**Comment by vriad** [comment]
Hm I kinda using `throws Error('Non-string type: number');` as pseudocode. 

I can't just change it to `throws ZodError('Non-string type: number')` because that's not technically accurate either. ZodErrors contain an array of error objects (not just an error message) and you can't initialize a ZodError like that. I think I'll leave it as is for demonstrative purposes. Anyone who wants to get into the weeds can read the Error Handling section for details.

Also you can avoid the `instanceof` check by just casting the error:

```ts
try {
  stringSchema.parse(12);
} catch (rawErr) {
  const zerr: z.ZodError = err;
  // handle
}
```
