### ISSUE TITLE
Support anyCase()/ignoreCase() for literals

### ISSUE THREAD

**Issue by xjrk58** [vriad/zod#70]
It would be great to have support for anyCase/ignoreCase for literals/enums. 
Example use case would be an API that accepts String enum and doesn't care about case.

**Comment by vriad** [comment]
Hey Jiri,

The nice thing about literals is that TypeScript statically enforces that value:

```ts
const tuna = z.literal("tuna");

type Tuna = z.infer<typeof tuna>; // "tuna"
const x: Tuna = "tUnA"; // TypeError 
```

If you're looking for something that is case-insensitive, then that literal static type mis-respresents your schema. I'm trying to keep Zod as rigorous as possible: the TypeScript types should hew as closely as possible to the type that is validated at runtime.

For now I'd recommend using a refinement for "ignoreCase" string literals. Note that the inferred type here is simply `string`:

```ts
const ignoreCaseTuna = z.string().refine(x => x.toLowercase() === "tuna");
```

If you really want the static type to be `"tuna"` instead of `string`, you could do this:

```ts
const ignoreCaseTuna: z.ZodType<"tuna"> = z.string().refine(x => x.toLowercase() === "tuna");
```

This gives you case insensitivity but still "hard codes" the static type of `"tuna"` by casting to z.ZodType.
