### ISSUE TITLE
All object properties are optional, but object cannot be empty

### ISSUE THREAD

**Issue by ivosabev** [vriad/zod#72]
I could not figure out how to write a rule that covers this scenario:

The object has `foo` and `bar` properties, that are optional
```
const Input = z.object({
  foo: z.number(),
  bar: z.string(),
}).partial();
```

You can pass `{foo: 1}`, `{bar: 'a'}` or `{foo: 1, bar: 'a'}, but `{}` should fail.

I guess I can do this with, `z.union`, but that seems like an overkill, especially if there are more than 2 object properties.

Seems to me that there should be a method that validates if an object is `{}`

**Comment by vriad** [comment]
Hey Ivo,

I would recommend using a custom refinement on the outer object:

```ts
const Input = z.object({
  foo: z.number(),
  bar: z.string(),
})
  .partial()
  .refine(data => Object.keys(data).length >= 1);
```

This actually isn't achievable with a union. because a this

```ts
z.union([
  z.object({ foo: z.number() }),
  z.object({ bar: z.string() })
])
```

would allow `{ foo: 12, bar: 12 }` or `{ foo: 'asdf', bar: 'asdf' }`. The data only needs to pass validation for one of the unioned types. As long as `foo` is a number, it wouldn't care whether `bar` is a string. So a refinement is your best bet.
