### ISSUE TITLE
Unions and enums from an array

### ISSUE THREAD

**Issue by ivosabev** [vriad/zod#73]
I might be missing something, but it seems this is currently not possible, but would be a great time/code saver:

```
const STATUSES = ['Assigned', 'In Progress', 'On Location', 'Succeeded', 'Failed'];
const StatusSchema = z.union(STATUSES.map(z.literal));
const StatusSchema2 = z.enum(STATUSES);
```

**Comment by vriad** [comment]
You did miss something :) 

https://github.com/vriad/zod#enums

**Comment by ivosabev** [comment]
I saw the docs, but the TS parser is throwing an error when you use a variable like the example I have shown above:

For `z.union`
```
Argument of type 'ZodLiteral<string>[]' is not assignable to parameter of type '[ZodType<any, ZodTypeDef>, ZodType<any, ZodTypeDef>, ...ZodType<any, ZodTypeDef>[]]'.
  Type 'ZodLiteral<string>[]' is missing the following properties from type '[ZodType<any, ZodTypeDef>, ZodType<any, ZodTypeDef>, ...ZodType<any, ZodTypeDef>[]]': 0, 1
```

For `z.enum`
```
Argument of type 'string[]' is not assignable to parameter of type '[string, ...string[]]'.
  Property '0' is missing in type 'string[]' but required in type '[string, ...string[]]'.
```

**Comment by vriad** [comment]
Yes I see. The documentation is definitely lacking here. 

You need to either need to pass the literal array directly into z.enum:
```ts
const FishEnum = z.enum(['Salmon', 'Tuna', 'Trout']);
``` 
or use `as const` (introduced in TypeScript 3.4):
```ts
const fishTypes = ['Salmon', 'Tuna', 'Trout'] as const;
const FishEnum = z.enum(fishTypes);
``` 
otherwise type inference won't work properly.

I just added this to the readme as well.

**Comment by vriad** [comment]
Also this won't work work similar reasons:

```ts
const StatusSchema = z.union(STATUSES.map(z.literal));
```

The reason for this is a little in the weeds. Basically these functions expect a tuple, not an array. The type of `STATUSES` is `string[]` but it needs to be a literal array: `['Assigned', 'In Progress', 'On Location', 'Succeeded', 'Failed']`. If you pass the array directly into z.enum or use `as const` then the TypeScript type engine views these things as literal types (i.e. tuples) instead of arrays.

**Comment by ivosabev** [comment]
With `as const` makes it `readonly`, but won't work either.

```typescript
const fishTypes = ['Salmon', 'Tuna', 'Trout'] as const;
const FishEnum = z.enum(fishTypes);
```

```
Argument of type 'readonly ["Salmon", "Tuna", "Trout"]' is not assignable to parameter of type '[string, ...string[]]'.
  The type 'readonly ["Salmon", "Tuna", "Trout"]' is 'readonly' and cannot be assigned to the mutable type '[string, ...string[]]'.
```

Maybe the internals of `z.enum` and `z.union` could be touched to allow such cases?

**Comment by dvargas92495** [comment]
hey @colinhacks I'm running into something similar here.

I have the following constant array:

```typescript
const WORK_TYPES = [
  { id: 1, name: "Task" },
  { id: 2, name: "Project" },
  { id: 3, name: "Initiative" },
] as const;
```

I'd like to create an enum type that is a union of the `name` fields of that array. Here's what I tried doing: 
```typescript
const workType = z.enum(WORK_TYPES.map((w) => w.name));
// Typescript: Source provides no match for required element at position 0 in target
```

What I think is happening is: `.map` produces a `<union of strings>[]`, which is technically not guaranteed to have a first element, despite `WORK_TYPES` being a constant. but the type of `enum` requires at least one element (which makes intuitive sense). 

This theory is supported by the following working:

```typescript
const workType = z.enum(
        [WORK_TYPES[0].name, ...WORK_TYPES.slice(1).map((w) => w.name)]
);
```

Any thoughts on a better workaround instead of ^? Or is this an issue with the `enum` input type?

**Comment by kevbook** [comment]
Maybe something like

```ts
const longArr = ['Salmon', 'Tuna', 'Trout'] as [string, ...string[]];
z.enum(longArr)
```
