### ISSUE TITLE
Zod V2

### ISSUE THREAD

**Issue by rossholdway** [vriad/zod#78]
Hi @vriad 

I've been looking for a solid JavaScript schema validation lib for awhile now and after trying out many, I’ve just found Zod! It looks great, thanks for creating it. I see that you've started work on a V2 and wanted to ask if there was a timeline for this? I'm just starting on a new project and would like to know if it's worth waiting.

Thanks,
Ross

**Comment by vriad** [comment]
Hey Ross,

There won't be many breaking changes in v2, so don't bother holding out for that release. There will be a super painless migration path. Mostly you'll just get access to a bunch of new functionality (better error customizability, data transformation, casting) without needing to refactor any code 🎉

Colin

**Comment by soulchild** [comment]
Hi Colin,

thanks for this awesome library!

I'll just piggyback on this issue as you mentioned "better error customizability": Will it be possible to hook into the error generation so that we'll be able to emit a custom error class? 

For now, I tried wrapping the `parse()` call with a custom function, but I failed at specifying the correct return type (and type for the `schema` parameter):

```ts
export const parseAndCatch = (schema: any, data:any): TYPE? => {
  try {
    return schema.parse(data);
  } catch(err) {
    if (err instanceof z.ZodError) {
      // transform err.errors and throw custom error class
    }
  }
} 
```

Any ideas?

Having the ability to directly customize the thrown error class would solve this nicely, I suppose.
